spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: 12345
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    properties.hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
  liquibase:
    change-log: db/changelog-master.yml
server:
  servlet.context-path: /api
  port: 7777
jwt:
  secret:
    mum: j321nt5j4bf1oi
    validityAccess: 600000
    validityRefresh: 1800000

